# Generated by Django 5.0.7 on 2024-09-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_nights',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
