# Generated by Django 5.0.7 on 2024-08-27 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0002_destination_itinerary_package_itinerarydestination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='destinations',
        ),
        migrations.RemoveField(
            model_name='itinerarydestination',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='package',
        ),
        migrations.RemoveField(
            model_name='itinerarydestination',
            name='itinerary',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='name',
            new_name='package_name',
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_number', models.PositiveIntegerField()),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TN_Api.package')),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_legs', to='TN_Api.location')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_legs', to='TN_Api.location')),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
        migrations.DeleteModel(
            name='ItineraryDestination',
        ),
    ]
