# Generated by Django 5.0.7 on 2024-09-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0003_booking_base_fare_booking_number_of_nights'),
    ]

    operations = [
    ]
