# Generated by Django 5.0.7 on 2024-09-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0004_auto_20240921_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverassignment',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='driverassignment',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
