# Generated by Django 5.0.7 on 2024-09-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0005_driverassignment_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='total_distance',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Total distance in kilometers', max_digits=10),
        ),
    ]
