# Generated by Django 5.0.7 on 2024-07-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0005_remove_user_first_name_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
