# Generated by Django 5.0.7 on 2024-08-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
