# Generated by Django 5.0.7 on 2024-09-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0006_package_total_distance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
    ]
