# Generated by Django 5.0.7 on 2024-09-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0007_alter_location_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated_package_fare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
