# Generated by Django 5.0.7 on 2024-08-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0008_driver_manager_user_role_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
