# Generated by Django 5.0.7 on 2024-09-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0008_booking_updated_package_fare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='updated_package_fare',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
