# Generated by Django 5.0.7 on 2024-08-23 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0009_alter_driver_license_number_delete_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_name', models.CharField(max_length=50, unique=True)),
                ('gas_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=15, unique=True)),
                ('date_bought', models.DateField()),
                ('registration_expiry_date', models.DateField()),
                ('max_passengers', models.IntegerField()),
                ('gas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TN_Api.gas')),
            ],
        ),
    ]
