# Generated by Django 5.0.7 on 2024-09-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0009_alter_booking_updated_package_fare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='gas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TN_Api.gas'),
        ),
    ]
