# Generated by Django 5.0.7 on 2024-12-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0010_alter_van_gas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
    ]
