# Generated by Django 5.0.7 on 2025-03-15 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0013_location_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_number', models.PositiveIntegerField()),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('original_leg_id', models.PositiveIntegerField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='TN_Api.booking')),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_end_legs', to='TN_Api.location')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_start_legs', to='TN_Api.location')),
            ],
            options={
                'ordering': ['leg_number'],
                'unique_together': {('booking', 'leg_number')},
            },
        ),
    ]
