# Generated by Django 5.0.7 on 2025-03-15 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0014_bookingleg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingleg',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_legs', to='TN_Api.booking'),
        ),
    ]
