# Generated by Django 5.0.7 on 2025-03-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0015_alter_bookingleg_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leg',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='leg',
            name='departure_time',
        ),
    ]
