# Generated by Django 5.0.7 on 2025-03-16 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TN_Api', '0016_remove_leg_arrival_time_remove_leg_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_final_location', to='TN_Api.location'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_starting_location', to='TN_Api.location'),
        ),
    ]
