from django.urls import path
from .views import (
    RegisterView, LoginView, LogoutView, UserDetailView, GetUserWithAdminRole,
    DriverCreateView,DriverListView,DriverDetailView,DriverUpdateView,DriverDeleteView, RetrieveDriverInstanceView,
    VanCreateView, VanListView, VanDetailView, VanUpdateView, VanDeleteView, UnassignedVanListView,
    GasCreateView, GasListView, GasDetailView, GasUpdateView, GasDeleteView,
    BookingCreateView, BookingListView, BookingDetailView, BookingUpdateView, BookingDeleteView, BookingPreviewView, UserBookingListView, GetBookingStatusListView, 
    ConfirmBookingView, CancelBookingView, StartBookingView, ConfirmJoinerPackageBookingsView,
    PackageCreateView, PackageListView, PackageDetailView, PackageUpdateView, PackageDeleteView, CalculatePackageFareView, JoinPackageView,
    PackageUserListView,
    DriverAssignmentList, DriverAssignmentByDriverList, DriverAssignmentRetrieveList, DriverActiveBookingsList, AvailableDriversForSwapView, SwapDriverView, GetDriverAssignment, CheckBookingDateConflictView,
    LocationValidationView, SetBookingLegActiveView, CompleteBookingLegView,
    RatingCreateView, RatingListView, RatingDetailView,
    ProcessPaymentView,
)

urlpatterns = [
    path('users/register/', RegisterView.as_view(), name='register'),
    path('users/login/', LoginView.as_view(), name='login'),
    path('users/logout/', LogoutView.as_view(), name='logout'),
    path('users/admin-user/', GetUserWithAdminRole.as_view(), name='admin-user'),
    path('users/<str:pk>/', UserDetailView.as_view(), name='get_user'),

    path('drivers/register/', DriverCreateView.as_view(), name='register_driver'),
    path('drivers/', DriverListView.as_view(), name='driver_list'),
    path('drivers/<str:id>/', DriverDetailView.as_view(), name='get_driver'),
    path('drivers/<str:id>/update/', DriverUpdateView.as_view(), name='update_driver'),
    path('drivers/<str:id>/delete/', DriverDeleteView.as_view(), name='delete_driver'),
    path('user-info/', RetrieveDriverInstanceView.as_view(), name='retrieve-driver-instance'),

    path('drivers-assignment/', DriverAssignmentList.as_view(), name='driver_assignment_list'),
    path('drivers-assignment/by-driver/', DriverAssignmentByDriverList.as_view(), name='driver_assignment_by_driver_list'),
    path('drivers-assignment/by-driver/active/', DriverActiveBookingsList.as_view(), name='driver-active-bookings'),
    path('driver-assignments/<str:driver_id>/', DriverAssignmentRetrieveList.as_view(), name='driver_assignment_detail'),
    path('driver-assignment/available-for-swap/', AvailableDriversForSwapView.as_view(), name='driver-available-for-swap'),
    path('driver-assignments/<str:id>/swap-driver/', SwapDriverView.as_view(), name='swap-driver'),
    path('drivers-assignment/retrieve/', GetDriverAssignment.as_view(), name='retrieve-driver-assigment'),

    path('vans/register/', VanCreateView.as_view(), name='register_van'),
    path('vans/', VanListView.as_view(), name='van_list'),
    path('vans/unassigned/', UnassignedVanListView.as_view(), name='unassigned_van_list'),
    path('vans/<str:pk>/', VanDetailView.as_view(), name='get_van'),
    path('vans/<str:pk>/update/', VanUpdateView.as_view(), name='update_van'),
    path('vans/<str:pk>/delete/', VanDeleteView.as_view(), name='delete_van'),

    path('gas/register/', GasCreateView.as_view(), name='register_gas'),
    path('gas/', GasListView.as_view(), name='gas_list'),
    path('gas/<str:pk>/', GasDetailView.as_view(), name='get_gas'),
    path('gas/<str:pk>/update/', GasUpdateView.as_view(), name='update_gas'),
    path('gas/<str:pk>/delete/', GasDeleteView.as_view(), name='delete_gas'),

    path('bookings/user-bookings/', UserBookingListView.as_view(), name='user-bookings'),
    path('bookings/confirm-joiner-package-bookings/', ConfirmJoinerPackageBookingsView.as_view(), name='confirm-joiner-package-bookings'),
    path('api/bookings/check-date-conflict/', CheckBookingDateConflictView.as_view(), name='check-booking-date-conflict'),
    path('bookings/status/<str:bookingstatus>/', GetBookingStatusListView.as_view(), name='booking-status'),
    path('bookings/', BookingListView.as_view(), name='booking-list'),
    path('bookings/preview-booking/', BookingPreviewView.as_view(), name='preview-bookin'),
    path('bookings/create/', BookingCreateView.as_view(), name='booking-create'),
    path('bookings/<str:pk>/', BookingDetailView.as_view(), name='booking-detail'),
    path('bookings/<str:pk>/update/', BookingUpdateView.as_view(), name='booking-update'),
    path('bookings/<str:pk>/delete/', BookingDeleteView.as_view(), name='booking-delete'),
    path('bookings/<str:pk>/confirm/', ConfirmBookingView.as_view(), name='booking-confirm'),
    path('bookings/<str:pk>/cancel/', CancelBookingView.as_view(), name='booking-cancel'),
    path('bookings/<str:pk>/start/', StartBookingView.as_view(), name='booking-start'),

    path('packages/calculate-fare/', CalculatePackageFareView.as_view(), name='calculate-package-fare'),
    path('packages/register/', PackageCreateView.as_view(), name='register_package'),
    path('packages/', PackageListView.as_view(), name='package_list'),
    path('packages/<str:pk>/', PackageDetailView.as_view(), name='get_package'),
    path('packages/<str:pk>/update/', PackageUpdateView.as_view(), name='update_package'),
    path('packages/<str:pk>/delete/', PackageDeleteView.as_view(), name='delete_package'),
    path('packages/<str:pk>/join/', JoinPackageView.as_view(), name='package-join'),
    path('packages/<str:pk>/users/', PackageUserListView.as_view(), name='package-users'),

    path('locations/check-coordinates/', LocationValidationView.as_view(), name='check-coordinates'),

    path('booking-legs/<int:pk>/to-active/', SetBookingLegActiveView.as_view(), name='activate-booking-leg'),
    path('booking-legs/<int:pk>/to-complete/', CompleteBookingLegView.as_view(), name='complete-booking-leg'),

    path('ratings/register/', RatingCreateView.as_view(), name='register-rating'),
    path('ratings/', RatingListView.as_view(), name='rating-list'),
    path('ratings/<int:pk>/', RatingDetailView.as_view(), name='rating-detail'),

    path('payments/process/', ProcessPaymentView.as_view(), name='process-payment'),
]